In [1]:
import torch
from transformers import RobertaTokenizerFast, RobertaForMaskedLM
model = RobertaForMaskedLM.from_pretrained('roberta-base')
tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')

In [2]:
text = f'In 1996, Lara <mask> <mask> was released on the playstation.'
inputs = tokenizer(text, return_tensors='pt')
outputs = model(**inputs)

In [3]:
is_masked = torch.where(
    inputs.input_ids == tokenizer.mask_token_id, 1, 0)
masked_idxs = torch.nonzero(is_masked)
probs= torch.softmax(outputs.logits[0, masked_idxs[:,1]], dim=1)

In [4]:
top_vocab_idxes = torch.topk(probs, 5)
for token_id in torch.transpose(top_vocab_idxes[1], 1, 0):
    print (tokenizer.decode(token_id))

 Cro 3
vellan
- 4
's 2
 Auto 64


In [5]:
confidences, token_ids = top_vocab_idxes

In [14]:
tokenizer.tokenize('Croft')

['Cro', 'ft']

In [11]:
token_ids[confidences.argmax(dim = 0)[0].item()][0]

tensor(6466)

In [16]:
CLOZE_MASKS = {
    'PERSON': 'IDENTITYMASK'}

In [185]:
argmaxes = [probs[i, x.item()].item() for i, x in enumerate(torch.argmax(probs, dim = 1))]

In [186]:
probs.shape

torch.Size([2, 50265])

In [187]:
top_vocab_idxes.values.shape

torch.Size([2, 1])

In [203]:
confidences, token_ids = top_vocab_idxes

In [204]:
token_ids

tensor([[6466],
        [ 155]])

In [205]:
confidences

tensor([[0.7073],
        [0.1745]], grad_fn=<TopkBackward>)

In [206]:
confidences.argmax(dim = 0)

tensor([0])

In [208]:
token_ids[confidences.argmax(dim=0)].item()

6466

In [210]:
test = torch.tensor([[1, 2, 3,], [4,5,6]])

In [219]:
test[confidences.argmax(dim=0)]

tensor([[1, 2, 3]])